version: '3.8'

services:
  pdf-search:
    build: .
    container_name: pdf-search-app
    ports:
      - "8501:8501"
    volumes:
      # PDF 파일 업로드 디렉토리
      - ./uploads:/app/uploads
      # 결과 저장 디렉토리
      - ./results:/app/results
      # 모델 캐시 디렉토리
      - model_cache:/root/.cache/torch/sentence_transformers
    environment:
      - PYTHONUNBUFFERED=1

  # 커맨드라인 버전
  pdf-search-cli:
    build: .
    container_name: pdf-search-cli
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
      - model_cache:/root/.cache/torch/sentence_transformers
    command: python pdf_search_cli.py
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  model_cache: 