version: '3.8'

services:
  embedding-test:
    build: .
    container_name: uvm-embedding-test
    volumes:
      # 모델 캐시를 호스트에 저장 (재다운로드 방지)
      - model_cache:/root/.cache/torch/sentence_transformers
      # 테스트 결과를 호스트에 저장
      - ./results:/app/results
      # 로컬 코드 개발용 (선택사항)
      - ./embedding_test.py:/app/embedding_test.py
    environment:
      - PYTHONUNBUFFERED=1
    # GPU 사용시 (NVIDIA Docker 필요)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  # Jupyter 노트북 서비스 (선택사항)
  jupyter:
    build: .
    container_name: uvm-jupyter
    ports:
      - "8888:8888"
    volumes:
      - model_cache:/root/.cache/torch/sentence_transformers
      - ./:/app
    command: >
      jupyter notebook 
      --ip=0.0.0.0 
      --port=8888 
      --no-browser 
      --allow-root 
      --NotebookApp.token=''
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  model_cache: 